package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.networktables.*;
import org.photonvision.PhotonCamera;
import org.photonvision.PhotonUtils;


     


/**
 *
 */
public class Vision extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//private LimeLight limelight;
private static NetworkTable table;
private static PhotonCamera camera;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    * Ca
    */
    public Vision() {
         
        table = NetworkTableInstance.getDefault().getTable("limelight");
        
        //29 1/4 at init
  }
}
 
 


     
    

//     @Override
//     public void periodic() {
//         // This method will be called once per scheduler run

//     }

//     @Override
//     public void simulationPeriodic() {
//         // This method will be called once per scheduler run when in simulation

//     }

//     // Put methods for controlling this subsystem
//     // here. Call these from Commands.

// }

