// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.auto;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.ProfiledPIDCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import frc.robot.subsystems.DriveTrain;
import edu.wpi.first.math.geometry.Pose2d;
import java.util.function.DoubleSupplier;
import frc.robot.Constants;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Autonomous {

    private DriveTrain driveTrain;
    private RobotContainer robotContainer;
    private double autoDistanceMeters = 2; //arbirary

    public Autonomous() {
        this.driveTrain = RobotContainer.getInstance().getDriveTrain();
    }

    public Command basicAuto() {
        return Commands.sequence(
            Commands.parallel(
                  new AutoDriveForward(driveTrain, autoDistanceMeters)
            ).withTimeout(Constants.AutoConstants.kSecUntilAutoCharge)
            // ,Commands.sequence(
            //     new AutoDriveToCharge(driveTrain),
            //     new AutoLevel(driveTrain))
            );
    }

}
